extends: airbnb/base
plugins: [
  import
]
rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
globals:
  describe: true
  it: true
  done: true
  beforeEach: true
  before: true
  afterEach: true
  after: true
