extends: airbnb/base
plugins: [
  import,
  chai-friendly,
]
rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  no-unused-expressions: 0
  chai-friendly/no-unused-expressions: 2
env:
  es6: true
  node: true
  mocha: true
